const { typeNameFromDir } = require("gatsby-transformer-csv")


module.exports = {
  pathPrefix: '/reponame',
  siteMetadata: {
    siteUrl: "https://www.yourdomain.tld",
    title: "Visualization Sketches",
  },
  plugins: [
    "gatsby-plugin-sass",

    "gatsby-plugin-mdx",
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "pages",
        path: "./src/pages/",
      },
      __key: "pages",
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data`,
        path: `${__dirname}/src/data/`,
      },
    },
    {
      resolve: `gatsby-transformer-csv`,
      options: {
        noheader: false,
        typeName: typeNameFromDir,
        nodePerFile: true,
      },
    },
  ],
};


// query MyQuery {
//   allDataCsv(filter: {}) {
//     edges {
//       node {
//         items {
//           date
//           entry_word_count
//           formatted_date
//           quarter
//         }
//       }
//     }
//   }
// }


const path = require("path")
exports.createPages = async ({ graphql, actions, reporter }) => {
  // Destructure the createPage function from the actions object
  const { createPage } = actions
  const result = await graphql(`
    query {
      allDataCsv {
        edges {
          node {
            items {
              date
              formatted_date
              entry_word_count
              quarter
            }
          }
        }
      }
    }
  `)
  if (result.errors) {
    reporter.panicOnBuild('🚨  ERROR: Loading "createPages" query')
  }
  // Create blog post pages.
  const posts = result
  // you'll call `createPage` for each result
  posts.forEach(({ node }, index) => {
    createPage({
      // The slug generated by gatsby-plugin-mdx doesn't contain a slash at the beginning
      // You can prepend it with any prefix you want
      path: `/blog/`,
      // This component will wrap our MDX content
      component: path.resolve(`./src/components/posts-page-layout.js`),
      // You can use the values in this context in
      // our page layout component
      context: { data: result },
    })
  })
}
